-- Estrutura inicial do ERP CEDEP.
-- Acesso pela Data API somente para usuários autenticados.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null default '',
  perfil text not null default 'Consulta'
    check (perfil in ('Administrador', 'Financeiro', 'Secretaria', 'Consulta')),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.erp_snapshots enable row level security;

revoke all on table public.profiles from anon;
revoke all on table public.erp_snapshots from anon;

grant select on table public.profiles to authenticated;
grant select, insert, update on table public.erp_snapshots to authenticated;
grant usage, select on sequence public.erp_snapshots_id_seq to authenticated;

drop policy if exists "Perfil visível pelo próprio usuário" on public.profiles;
create policy "Perfil visível pelo próprio usuário"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Snapshot visível pelo proprietário" on public.erp_snapshots;
create policy "Snapshot visível pelo proprietário"
on public.erp_snapshots
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Snapshot criado pelo proprietário" on public.erp_snapshots;
create policy "Snapshot criado pelo proprietário"
on public.erp_snapshots
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Snapshot atualizado pelo proprietário" on public.erp_snapshots;
create policy "Snapshot atualizado pelo proprietário"
on public.erp_snapshots
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create schema if not exists private;

create or replace function private.criar_perfil_inicial()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, nome)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nome', '')
  );
  return new;
end;
$$;

revoke all on function private.criar_perfil_inicial() from public;
revoke all on function private.criar_perfil_inicial() from anon;
revoke all on function private.criar_perfil_inicial() from authenticated;

drop trigger if exists ao_criar_usuario on auth.users;
create trigger ao_criar_usuario
after insert on auth.users
for each row execute procedure private.criar_perfil_inicial();

-- A função abaixo é criada pelo recurso "RLS automático" do projeto.
-- O gatilho interno continua funcionando sem permitir chamadas pela API.
revoke execute on function public.rls_auto_enable() from public;
revoke execute on function public.rls_auto_enable() from anon;
revoke execute on function public.rls_auto_enable() from authenticated;
